
name: "Docker CI"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        id: docker_buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Build
        run: |
          echo ${{ secrets.DOCKER_LOGIN }} | docker login -u ${{ github.actor }} --password-stdin
          docker buildx create --use
          docker buildx inspect --bootstrap
          VERSION=$(node -p "require('./package.json').version")
          APP=$(node -p "require('./package.json').name")

          echo "Build: ${APP}.${VERSION}" 

          docker buildx build \
             --push \
            --no-cache \
            --build-arg VERSION=$VERSION \
            -t ${{ github.actor }}/${APP}:$VERSION \
            -f .docker/Dockerfile \
            .

          docker tag ${{ github.actor }}/${APP}:$VERSION ${{ github.actor }}/${APP}:latest
          docker push ${{ github.actor }}/${APP}:latest

          echo "${{ github.actor }}/${APP}:${VERSION}" 
          echo "${{ github.actor }}/${APP}:latest"